namespace IdiotProof.Models;

/// <summary>
/// A trade signal generated by a strategy evaluation.
/// </summary>
public sealed class TradeSignal
{
    public string Symbol { get; init; } = string.Empty;
    public TradeDirection Direction { get; init; }
    public decimal ConfidencePercent { get; init; }
    public decimal SuggestedEntry { get; init; }
    public decimal SuggestedStop { get; init; }
    public List<decimal> Targets { get; init; } = [];
    public string Reason { get; init; } = string.Empty;
    public string StrategyName { get; init; } = string.Empty;
    public DateTime GeneratedUtc { get; init; } = DateTime.UtcNow;
}

/// <summary>
/// A completed trade execution record.
/// </summary>
public sealed class TradeExecution
{
    public string ExecutionId { get; init; } = Guid.NewGuid().ToString("N")[..8];
    public string Symbol { get; init; } = string.Empty;
    public OrderSide Side { get; init; }
    public decimal Price { get; init; }
    public int Quantity { get; init; }
    public DateTime ExecutedUtc { get; init; } = DateTime.UtcNow;
    public string BrokerOrderId { get; init; } = string.Empty;
}

/// <summary>
/// Request to place an order with a broker.
/// </summary>
public sealed class OrderRequest
{
    public string Symbol { get; init; } = string.Empty;
    public int Quantity { get; init; }
    public OrderSide Side { get; init; }
    public OrderType Type { get; init; }
    public decimal? LimitPrice { get; init; }
    public string TimeInForce { get; init; } = "DAY";
}

/// <summary>
/// Result of an order placement attempt.
/// </summary>
public sealed class OrderResult
{
    public string BrokerOrderId { get; init; } = string.Empty;
    public bool IsSuccess { get; init; }
    public string? Message { get; init; }
}

/// <summary>
/// A position held with a broker.
/// </summary>
public sealed class Position
{
    public string Symbol { get; init; } = string.Empty;
    public int Quantity { get; init; }
    public decimal AveragePrice { get; init; }
    public decimal MarketValue { get; init; }
    public decimal UnrealizedPnl { get; init; }
}

/// <summary>
/// Latest price snapshot from a data feed.
/// </summary>
public sealed record LatestPrice(
    string Symbol,
    decimal Price,
    DateTime TimestampUtc,
    string Source);

/// <summary>
/// Pre-calculated trade setup ready for execution.
/// </summary>
public sealed class TradeSetup
{
    public string SetupId { get; set; } = Guid.NewGuid().ToString("N")[..8];
    public DateTime GeneratedUtc { get; set; } = DateTime.UtcNow;
    public DateTime ExpiresUtc { get; set; } = DateTime.UtcNow.AddMinutes(10);

    public string Symbol { get; set; } = "";
    public string? CompanyName { get; set; }
    public TradeDirection Direction { get; set; }
    public bool IsLong => Direction == TradeDirection.Long;

    public decimal EntryPrice { get; set; }
    public OrderType EntryType { get; set; } = OrderType.Limit;

    public decimal StopLoss { get; set; }
    public decimal TakeProfit { get; set; }
    public decimal TrailingStopPercent { get; set; }

    public int Quantity { get; set; }
    public decimal RiskDollars { get; set; }
    public decimal RewardDollars { get; set; }
    public decimal RiskRewardRatio => RiskDollars > 0 ? RewardDollars / RiskDollars : 0;

    public int ConfidenceScore { get; set; }
    public ConfidenceGrade Grade => ConfidenceScore switch
    {
        >= 85 => ConfidenceGrade.APlus,
        >= 75 => ConfidenceGrade.A,
        >= 65 => ConfidenceGrade.B,
        >= 55 => ConfidenceGrade.C,
        >= 45 => ConfidenceGrade.D,
        _ => ConfidenceGrade.F
    };

    public string Rationale { get; set; } = "";
    public List<string> BullishFactors { get; set; } = [];
    public List<string> BearishFactors { get; set; } = [];
    public bool IsExpired => DateTime.UtcNow > ExpiresUtc;
}

/// <summary>
/// Risk limits to prevent catastrophic losses.
/// </summary>
public sealed class RiskLimits
{
    public decimal MaxLossPerTrade { get; set; } = 100m;
    public decimal MaxLossPerDay { get; set; } = 500m;
    public decimal MaxPositionSize { get; set; } = 5000m;
    public decimal MaxAccountPercentPerTrade { get; set; } = 2m;
    public decimal MinRiskRewardRatio { get; set; } = 1.5m;
    public int MinConfidenceScore { get; set; } = 50;
    public int MaxOpenPositions { get; set; } = 5;
}
