namespace IdiotProof.Models;

/// <summary>
/// A trade signal generated by a strategy evaluation.
/// </summary>
public sealed class TradeSignal
{
    public string Symbol { get; init; } = string.Empty;
    public TradeDirection Direction { get; init; }
    public decimal ConfidencePercent { get; init; }
    public decimal SuggestedEntry { get; init; }
    public decimal SuggestedStop { get; init; }
    public List<decimal> Targets { get; init; } = [];
    public string Reason { get; init; } = string.Empty;
    public string StrategyName { get; init; } = string.Empty;
    public DateTime GeneratedUtc { get; init; } = DateTime.UtcNow;
    /// <summary>
    /// Identity user ID of the account that generated this signal. Mutable on purpose:
    /// strategies are pure (they don't know about users) and the execution service stamps
    /// this after the signal is produced. If/when signal stamping moves into a factory,
    /// this should become init-only.
    /// </summary>
    public string UserId { get; set; } = string.Empty;
}

/// <summary>
/// A completed trade execution record.
/// </summary>
public sealed class TradeExecution
{
    public string ExecutionId { get; init; } = Guid.NewGuid().ToString("N")[..8];
    public string Symbol { get; init; } = string.Empty;
    public OrderSide Side { get; init; }
    public decimal Price { get; init; }
    public int Quantity { get; init; }
    public DateTime ExecutedUtc { get; init; } = DateTime.UtcNow;
    public string BrokerOrderId { get; init; } = string.Empty;
}

/// <summary>
/// Request to place an order with a broker. Either <see cref="Quantity"/>
/// (share count) or <see cref="Notional"/> (dollar amount) sizes the order;
/// brokers that support both (Alpaca) route whichever is set, with Quantity
/// winning when both are populated. The DSL prevents the "both" case at
/// authoring time but the broker layer is defensive anyway.
/// </summary>
public sealed class OrderRequest
{
    public string Symbol { get; init; } = string.Empty;

    /// <summary>Share count. <c>0</c> when the order is notionally sized.</summary>
    public int Quantity { get; init; }

    /// <summary>
    /// Dollar amount (Alpaca <c>notional</c> field). Null when the order is
    /// share-sized. Brokers that don't support notional should reject with a
    /// helpful message rather than silently fall back to a guess.
    /// </summary>
    public decimal? Notional { get; init; }

    public OrderSide Side { get; init; }
    public OrderType Type { get; init; }
    public decimal? LimitPrice { get; init; }

    /// <summary>
    /// Stop trigger price for <see cref="OrderType.Stop"/> / <see cref="OrderType.StopLimit"/>.
    /// Null for other order types.
    /// </summary>
    public decimal? StopPrice { get; init; }

    /// <summary>
    /// Trail amount (percent) for <see cref="OrderType.TrailingStop"/>. Null otherwise.
    /// </summary>
    public decimal? TrailPercent { get; init; }

    public string TimeInForce { get; init; } = "DAY";

    /// <summary>
    /// Route the order to the extended-hours session (premarket 4:00–9:30 /
    /// after-hours 16:00–20:00 ET). Alpaca requires <c>extended_hours=true</c>
    /// AND a limit order with DAY time-in-force — otherwise a premarket order
    /// silently queues until the 9:30 bell, which defeats a gapper entry.
    /// </summary>
    public bool ExtendedHours { get; init; }
}

/// <summary>
/// Result of an order placement attempt.
/// </summary>
public sealed class OrderResult
{
    public string BrokerOrderId { get; init; } = string.Empty;
    public bool IsSuccess { get; init; }
    public string? Message { get; init; }
}

/// <summary>
/// A position held with a broker.
/// </summary>
public sealed class Position
{
    public string Symbol { get; init; } = string.Empty;

    /// <summary>
    /// Net shares held. <c>decimal</c> (not <c>int</c>) so fractional-share positions
    /// (Alpaca returns e.g. "2.5") survive and short positions keep their negative sign.
    /// </summary>
    public decimal Quantity { get; init; }
    public decimal AveragePrice { get; init; }
    public decimal MarketValue { get; init; }
    public decimal UnrealizedPnl { get; init; }
}

/// <summary>
/// Latest price snapshot from a data feed.
/// </summary>
public sealed record LatestPrice(
    string Symbol,
    decimal Price,
    DateTime TimestampUtc,
    string Source);

/// <summary>
/// Pre-calculated trade setup ready for execution. Canonical, decimal-based, immutable.
/// All money/price fields are <c>decimal</c> to avoid binary float drift on prices.
/// </summary>
public sealed class TradeSetup
{
    public string SetupId { get; init; } = Guid.NewGuid().ToString("N")[..8];
    public DateTime GeneratedUtc { get; init; } = DateTime.UtcNow;
    public DateTime ExpiresUtc { get; init; } = DateTime.UtcNow.AddMinutes(10);

    public string Symbol { get; init; } = "";
    public string? CompanyName { get; init; }
    public TradeDirection Direction { get; init; }
    public bool IsLong => Direction == TradeDirection.Long;

    public decimal EntryPrice { get; init; }
    public OrderType EntryType { get; init; } = OrderType.Limit;

    public decimal StopLoss { get; init; }
    public decimal TakeProfit { get; init; }
    public decimal TrailingStopPercent { get; init; }

    public int Quantity { get; init; }
    public decimal RiskDollars { get; init; }
    public decimal RewardDollars { get; init; }
    public decimal RiskRewardRatio => RiskDollars > 0 ? RewardDollars / RiskDollars : 0;

    public int ConfidenceScore { get; init; }
    public ConfidenceGrade Grade => ConfidenceScore switch
    {
        >= 85 => ConfidenceGrade.APlus,
        >= 75 => ConfidenceGrade.A,
        >= 65 => ConfidenceGrade.B,
        >= 55 => ConfidenceGrade.C,
        >= 45 => ConfidenceGrade.D,
        _ => ConfidenceGrade.F
    };

    public string Rationale { get; init; } = "";
    public List<string> BullishFactors { get; init; } = [];
    public List<string> BearishFactors { get; init; } = [];

    public bool IsExpired => DateTime.UtcNow > ExpiresUtc;

    /// <summary>Time remaining before this setup expires. Negative when already expired.</summary>
    public TimeSpan ExpiresIn => ExpiresUtc - DateTime.UtcNow;

    /// <summary>
    /// Internal consistency check: positive sizing, stop on the correct side of entry,
    /// confidence in [0,100]. Stricter rules (per-trade and daily risk caps) are enforced
    /// by <see cref="IdiotProof.Shared.Risk.RiskGuardian"/>.
    /// </summary>
    public bool IsWellFormed
    {
        get
        {
            if (Quantity <= 0) return false;
            if (EntryPrice <= 0m || StopLoss <= 0m || TakeProfit <= 0m) return false;
            if (ConfidenceScore < 0 || ConfidenceScore > 100) return false;
            if (Direction == TradeDirection.Long && (StopLoss >= EntryPrice || TakeProfit <= EntryPrice)) return false;
            if (Direction == TradeDirection.Short && (StopLoss <= EntryPrice || TakeProfit >= EntryPrice)) return false;
            return true;
        }
    }
}

/// <summary>
/// Risk limits to prevent catastrophic losses.
/// </summary>
public sealed class RiskLimits
{
    public decimal MaxLossPerTrade { get; set; } = 100m;
    public decimal MaxLossPerDay { get; set; } = 500m;
    public decimal MaxPositionSize { get; set; } = 5000m;
    public decimal MaxAccountPercentPerTrade { get; set; } = 2m;
    public decimal MinRiskRewardRatio { get; set; } = 1.5m;
    public int MinConfidenceScore { get; set; } = 50;
    public int MaxOpenPositions { get; set; } = 5;
}
